repos:
  - repo: local
    hooks:
      - id: fmt
        name: fmt
        entry: cargo fmt
        language: system
        always_run: true
        pass_filenames: false
  - repo: local
    hooks:
      - id: test
        name: test
        entry: cargo test
        language: system
        always_run: true
        pass_filenames: false